### ISSUE TITLE
HW04 - ArrayGen

### ISSUE THREAD

**Issue by chulderman** [chulderman/punctualPears#1]
This class is responsible for generating an int[] array that JCFIteratorDemo.java will use to fill the other
JCF Data Structures.

**Comment by chulderman** [comment]
@mjmillan - Is this done? It doesn't seem like there's an accessor method for the integer array.

**Comment by chulderman** [comment]
Nevermind. Noticed that you create the array and return it simultaneously. Is this best practice? Maybe it is...

**Comment by ghost** [comment]
This allows ArrayGen to be used to generate multiple arrays if necessary. My thought was this class only creates the array, it doesn't need to keep track of it later use.

**Comment by chulderman** [comment]
@mjmillan - I would suggest changing how this is written.

You should have an explicit accessor for the int array, the int[] creation method should be called in the constructor and be private. New ArrayGen's of different size would be created explicitly. Otherwise there should be a public mutator to accomplish this. I'd prefer the former.
