### ISSUE TITLE
HW04 - ArrayListGen

### ISSUE THREAD

**Issue by chulderman** [chulderman/punctualPears#2]
This class is responsible for generating an ArrayList of Integers; it will be filled by the int[] array generated by the ArrayGen.java class.

**Comment by chulderman** [comment]
Use something like [this](https://github.com/chulderman/punctualPears/blob/linked_list_gen/source/edu/oakland/helper/LinkedListGen.java#L72) to create an iterator for your ArrayListGen.

Make sure that it conforms to [this](https://github.com/chulderman/punctualPears/blob/linked_list_gen/source/edu/oakland/helper/LinkedListGen.java#L61) usage.

**Comment by ghost** [comment]
ArrayListGen is complete, I will close this issue.

**Comment by ghost** [comment]
This class is now finished and works properly so I will close this issue,

**Comment by chulderman** [comment]
[populateArrayList](https://github.com/chulderman/punctualPears/blob/master/source/edu/oakland/helper/ArrayListGen.java#L42) should return void IMHO. Access to the ArrayListGen should be explicit through an accessor method.

**Comment by chulderman** [comment]
Rather than look at the index and do a comparison for hasNext() maybe we should be doing a try catch to determine if there is an Integer at that index. If it doesn't throw an exception return true. 

https://github.com/chulderman/punctualPears/blob/master/source/edu/oakland/helper/ArrayListGen.java#L140
