### ISSUE TITLE
HW04 - LinkedListGen

### ISSUE THREAD

**Issue by chulderman** [chulderman/punctualPears#4]
This class is responsible for generating the SinglyLinkedList<SingleLink> from SinglLinks created by the SingleLink class

**Comment by chulderman** [comment]
Waiting for issue #2 to close before merging back into master. Latest - https://github.com/chulderman/punctualPears/commit/6c8dde98985528ebfacc76d6edd54b3adba63caa

**Comment by ghost** [comment]
I had to fix some errors in LinkedListGen in order to resolve issue 5, and as a result I believe we can close both issue 4 and 5.

**Comment by ghost** [comment]
I'm reopening this issue since LinkedListGen needs to be reworked so that it works with the updated JCFIteratorDemo. I shouldn't use ArrayListGen anymore, and the SingleLinks need to be built using the integer array.
