### ISSUE TITLE
HW04 - JCFIteratorDemo

### ISSUE THREAD

**Issue by chulderman** [chulderman/punctualPears#5]
1. The “main()” method in the JCFIteratorDemo class is called the start the App.
2. The JCFIteratorDemo class then directs the ArrayGen class to generate an int[] array with 20 elements, having ascending values from 1 through 20.
3. The JCFIterator class is passed the reference to this array. The JCFIteratorDemo class then directs the ArrayListGen class to generate an ArrayList<Integer>; it is then filled with the elements from the int[] array;
4. The JCFIteratorDemo class then builds an Iterator class that finds all the odd elementsin the ArrayList<Integer> class and prints them to the command line;
5. The JCFDemo class then directs the SingleLink class to build a SinglyLinkedList<Integer> and fill it with elements from the int[] array. The SingleLink class will then pass the reference to this SinglyLinkedList<SingleLink> back to the JCFIteratorDemo class.
6. The JCFIteratorDemo class then builds an Iterator to find all the even elements within the SinglyLinkedList<SingleLink> and print them to the command line;

**Comment by chulderman** [comment]
Most of this is done already. This will be the last issue to close.

**Comment by ghost** [comment]
I will work finishing this up now. If I find any errors in any of the classes I'll try and fix them and let you know if I get stuck

**Comment by ghost** [comment]
Everything appears to work properly now, so I'll close this issue.

**Comment by ghost** [comment]
This should be finished now, but I will wait to close it until everything else completed. I won't be merging anything back up to master until you've looked at it all, so please work off my branch when you get around to it.

**Comment by chulderman** [comment]
@mjmillan - It'd be nice to change this to static. The constructor would be private and then we'd implement final values and static methods. It doesn't make sense for this to have instances. It makes no semantic sense.

**Comment by ghost** [comment]
Professor Brooks specially said not to do that in class (if I understand your suggestion properly).
